# -*- coding: utf-8 -*-
"""Copy of Basic of C++.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHk4f1EsfexRfJ4rEmmK02frHzixNmZb
"""

!apt-get --purge remove cuda nvidia* libnvidia-*
!dpkg -l | grep cuda- | awk '{print $2}' | xargs -n1 dpkg --purge
!apt-get remove cuda-*
!apt autoremove
!apt-get update

!wget https://developer.nvidia.com/compute/cuda/9.2/Prod/local_installers/cuda-repo-ubuntu1604-9-2-local_9.2.88-1_amd64 -O cuda-repo-ubuntu1604-9-2-local_9.2.88-1_amd64.deb
!dpkg -i cuda-repo-ubuntu1604-9-2-local_9.2.88-1_amd64.deb
!apt-key add /var/cuda-repo-9-2-local/7fa2af80.pub
!apt-get update
!apt-get install cuda-9.2

!nvcc --version

!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git

# Commented out IPython magic to ensure Python compatibility.
# %load_ext nvcc_plugin

"""#**Introduction** 

C++ (pronounced see plus plus) is a general purpose programming language that is free-form and compiled. It is regarded as an intermediate-level language, as it comprises both high-level and low-level language features. It provides imperative, object-oriented and generic programming features.

C++ is one of the most popular programming languages and is implemented on a wide variety of hardware and operating system platforms. As an efficient performance driven programming language it is used in systems software, application software, device drivers, embedded software, high-performance server and client applications, and entertainment software such as video games. Various entities provide both open source and proprietary C++ compiler software, including the FSF, LLVM, Microsoft and Intel

**What is C++**
C++ is a cross-platform language that can be used to create high-performance applications.

**Who developed C++**
C++ was developed by Bjarne Stroustrup.

#1- **Hellow Words**
Every C++ program uses libraries, which give the ability to execute necessary functions. For example, the most basic function called 'cout', which prints to the screen, is defined in the iostream header file.

To add the ability to run the cout command to our program, we must add following include directive to our first line of the code:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#   cout << "Goodbye, World!" << std::endl;
#   return 0;
# }

"""#2-**Comments** 
Comments can be used to explain C++ code, and to make it more readable. It can also be used to prevent execution when testing alternative code. Comments can be singled-lined or multi-lined.

Single-line comments start with two forward slashes (//).

Any text between // and the end of the line is ignored by the compiler (will not be executed).

This example uses a single-line comment before a line of code:




"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# /* hellow wors 
# sdfdf
# */
# #include <iostream>
# using namespace std; // it used for explaination 
# 
# int main() {
#   cout << "Goodbye, World!" << std::endl;
#   return 0;
# }

"""#3-**C++ User Input** 

.You have already learned that cout is used to output (print) values. Now we will use cin to get user input.

.cin is a predefined variable that reads data from the keyboard with the extraction operator (>>).
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# 
# #include <iostream>
# using namespace std; // it used for explaination 
# 
# int main() {
#   int x=0; 
# cout << "Type a number: "; // Type a number and press enter
# cin >> x; // Get user input from the keyboard
# cout << "Your number is: " << x; // Display the input value
# }

"""#4-**Variable and types** 

**Data types**

C++ provides a rich set of built-in as well as user defined data types. Following table lists down seven basic C++ data types:

**Built-in**
- Boolean - boolean - either true or false (Size 4 bytes).
- Integers - whole numbers which can be both positive and negative. Defined using char, int.(Size 4 bytes)
- Floating point numbers - real numbers (numbers with - fractions). Defined using float and double (Size 4 bytes)
- Double - Stores Fractional numbers.Containing one or more decimals (size 8 bytes )
- Char - Stores a Single Characters
Valueless using the void keyword
Wide character using the wchar_t keyword(Size 1 bytes)

**Typdefs**
Typedefs allow for creating new names (think of them as aliases) for existing types. Following is the simple syntax to define a new type using typedef:

**Defining variables**
For numbers, we will usually use the type int, which an integer in the size of a "word" the default number size of the machine which your program is compiled on. On most computers today, it is a 32-bit number, which means the number can range from -2,147,483,648 to 2,147,483,647 (same as long).

To define the variables foo and bar, we need to use the following syntax:

int foo;

int bar = 1;

The variable foo can be used, but since we did not initialize it, we don't know what's in it. The variable bar contains the number 1.

Now, we can do some math. Assuming a, b, c, d, and e are variables, we can simply use plus, minus and multiplication operators in the following notation, and assign a new value to a:

int a = 0, b = 1, c = 2, d = 3, e = 4;

a = b - c + d * e;

cout << a << endl; // will print 1-2+3*4 = 11


"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#   int a = 3;
#   float b = 4.5;
#   double c = 5.25;
#   double sum;
# 
#   /* Your code goes here */
#     sum =a+b+c;
# 
#   cout << "The sum of a, b, and c is" << sum << endl;
#   return 0;
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
#  
# int main () {
#   int myNum = 1000;
#   cout << myNum;
#   return 0;
# }
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     float mynumb=2.25;
#     cout <<mynumb;
#     return 0;
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     double mynumb=66.87;
#     cout <<mynumb;
#     return 0;
#     
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namesapace std;
# 
# int main() {
#   int x = 5;
#   int y = 3;
#   cout << x + y;
#   return 0;
# }
# 
#

"""##4.1**-Strings**
Strings are used for storing text.

A string variable contains a collection of characters surrounded by double quotes

"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     string shahzad = "hello";
#     cout << shahzad;
#     return 0;
# }
#

"""# 5-**C++ Operators** 
Operators are used to perform operations on variables and values.

In the example below, we use the + operator to add together two values:

## 5.1**Arithmetic Operators**
Arithmetic operators are used to perform common mathematical operations.

.(+)  (Addition) 	(Adds together two values)  	(x + y)

.(-) 	(Subtraction)	(Subtracts one value from another)	(x - y)

.(*) (Multiplication) 	(Multiplies two values) 	(x * y)

.(/) 	(Division) 	(Divides one value by another) 	(x / y)

.(%) 	(Modulus) 	(Returns the division remainder) 	(x % y)

.(++) 	(Increment) 	(Increases the value of a variable by 1) 	(++x)

.(--) 	(Decrement) 	(Decreases the value of a variable by 1) 	(--x)
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream> 
# using namespace std;
# 
# int main(){
#     int a = 7;
#     int b = 6;
#     int resultplus;
#     resultplus=a+b;
#     int resultminus;
#     resultminus=a-b;
#     int resultmultiplaction;
#     resultmultiplaction=a*b;
#     int resultdivision;
#     resultdivision=a/b;
#     cout <<"additiona+b="<<resultplus<<endl;
#     cout <<"minusa-b="<<resultminus<<endl;
#     cout <<"resultmultiplactiona*b="<<resultmultiplaction<<endl;
#     cout <<"divisiona/b="<<resultdivision<<endl;
#     return 0;
# }
#

"""#**5.2Assignment Operators** 

Assignment operators are used to assign values to variables.

In the example below, we use the assignment operator (=) to assign the value 10 to a variable called x:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int a; // this is definition of assignment
#     a = 2; //
#     cout <<a<<endl;
#     return 0;
# }

"""## 5.3**Comparison Operators** 

Comparison operators are used to compare two values.

Note: The return value of a comparison is either true (1) or false (0).

In the following example, we use the greater than operator (>) to find out if 5 is greater than 3:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int a =5;
#     int b =4;
#     cout <<(a>b)<<endl;
#     return 0;
# }
#

"""##5.4**Logical Operators** 
Logical operators are used to determine the logic between variables or values:


"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int a=3;
#     int b=5;
#     cout <<(a>3 && a<7)<<endl; // returns true (1) because 3 is greater than 2 AND 2 is less than 3
#     cout <<(b>3 || b<4)<<endl; // returns true (1) because one of the conditions are true (5 is greater than 3, but 5 is not less than 4)
#     return 0;
# }
#

"""#6-**C++ Math**
C++ has many functions that allows you to perform mathematical tasks on numbers.

##6.1-**Max and min** 
The max(x,y) function can be used to find the highest value of x and y:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int a;
#     a = 2;
#     int b;
#     b = 5;
#     cout <<max(a,b)<<endl; // this function is used to find max value between two
#     // value
#     cout <<min(a,b)<<endl; // this function is used to find min values beteen
#    // two  value
#     return 0;
# }
#

"""##6.2-**math Header** 
Other functions, such as sqrt (square root), round (rounds a number) and log (natural logarithm), can be found in the <cmath> header file:

"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# #include <cmath>
# using namespace std;
# 
# int main(){
#     int a;
#     a = 4;
#     int b;
#     b = -2;
#     cout <<"square value of a="<<sqrt(a)<<endl; // sqrt function is used to find squar root of varia
#     cout <<"absolate vale of b="<<abs(b)<<endl; 
# }
# 
# 
#

"""#7-**C++ Booleans** 
Very often, in programming, you will need a data type that can only have one of two values, like:

YES / NO

ON / OFF

TRUE / FALSE


For this, C++ has a bool data type, which can take the values true (1) or false (0).


"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# int main(){
#     bool a =true;
#     bool b =false;
#     cout <<a<<endl;
#     cout <<b<<endl;
#     return 0;
# }
#

"""##**7.1-Boolean Expression**
A Boolean expression is a C++ expression that returns a boolean value: 1 (true) or 0 (false).

You can use a comparison operator, such as the greater than (>) operator to find out if an expression (or a variable) is true:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#            int a;
#            a = 2;
#            int b;
#            b = 1;
#            cout <<"true and false"<<(a>b)<<endl;
#            return 0;
# }
#

"""#**8-C++ Conditions and If Statements**
C++ supports the usual logical conditions from mathematics:

- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b
- Equal to a == b
- Not Equal to: a != b
- You can use these conditions to perform different actions for different decisions.

C++ has the following conditional statements:

- Use if to specify a block of code to be executed, if a specified condition is true
- Use else to specify a block of code to be executed, if the same condition is false
- Use else if to specify a new condition to test, if the first condition is false
- Use switch to specify many alternative blocks of code to be executed

##**8.1-The if Statement**
Use the if statement to specify a block of C++ code to be executed if a condition is true.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     if (5>10) {
#         cout <<"20 is greater than 10"<<endl;
#     }
#     cout <<"main body exution"<<endl;
#     return 0;
# }
#

"""##**-8.2The else Statement** 
Use the else statement to specify a block of code to be executed if the condition is false.
"""

#include <iostream>
using namespace std;

int main() {
  int time = 20;
  if (time < 18) {
    cout << "Good day.";
  } else {
    cout << "Good evening.";
  }
  return 0;
}

"""##**8.3-The else if Statement** 
Use the else if statement to specify a new condition if the first condition is false.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#   int time = 22;
#   if (time < 10) {
#     cout << "Good morning.";
#   } else if (time < 20) {
#     cout << "Good day.";
#   } else {
#     cout << "Good evening.";
#   }
#   return 0;
# }
#

"""#**9-C++ Switch Statements** 
Use the switch statement to select one of many code blocks to be executed.
This is how it works:
-  The switch expression is evaluated once
- The value of the expression is compared with the values of each case
- If there is a match, the associated block of code is executed
- The break and default keywords are optional, and will be described later in this chapter
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int day=9;
#     switch(day){
#      case 1:
#      cout <<"monday"; 
#      break;  
#      case 2:
#      cout <<"tuesday";
#      break;
#      default:
#      cout <<"no case matches";
#     }
#     return 0;
# }
#

"""**The break Keyword**

When C++ reaches a break keyword, it breaks out of the switch block.

This will stop the execution of more code and case testing inside the block.

When a match is found, and the job is done, it's time for a break. There is no need for more testing.

A break can save a lot of execution time because it "ignores" the execution of all the rest of the code in the switch block.

**The default Keyword**

The default keyword specifies some code to run if there is no case match:

#**10-Loop**
Loops can execute a block of code as long as a specified condition is reached.

Loops are handy because they save time, reduce errors, and they make code more readable.

**While Loop**

The while loop loops through a block of code as long as a specified condition is true:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int i =0;
#     while (i<5){
#         cout <<"shahzad"<<"\n";
#         i++;
#     }
#     return 0;
# }
#

"""##**10.1-The Do/While Loop**
 - The do/while loop is a variant of the while loop. 
 -This loop will execute the code block once, before checking if the condition is true, then it will repeat the loop as long as the condition is true.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#     int i =9;
#     do{
#         cout <<"shahzad"<<"\n";
#        i++;
#     }
#     while(i<5);
#     return 0;
# }
#

"""##**10.2-C++ Break**
The break statement can also be used to jump out of a loop.

This example jumps out of the loop when i is equal to 4:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main(){
#      for (int i = 0; i < 14; i++) {
#          if (i == 8){
#           break;
#          }
#     cout << i << "\n";
#   } 
#   return 0;
# }
# 
#

"""##**10.3-C++ Continue** 

The continue statement breaks one iteration (in the loop), if a specified condition occurs, and continues with the next iteration in the loop.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# int main(){
#     for (int i = 0; i < 12; i++) {
#         if (i == 7){
#             continue;
#         }
#         cout <<i<<"\n";
#     }
#     return 0;
# }
#

"""#**11-C++ Arrays** 
Arrays are used to store multiple values in a single variable, instead of declaring separate variables for each value.

To declare an array, define the variable type, specify the name of the array followed by square brackets and specify the number of elements it should store:

**string cars[4];**

To create an array of three integers, you could write:
**int myNum[3] = {10, 20, 30};**

**Access the Elements of an Array**

You access an array element by referring to the index number.

This statement accesses the value of the first element in cars:

string cars[4] = {"Volvo", "BMW", "Ford", "Mazda"};
cout << cars[0];
// Outputs Volvo
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# #include <string>
# using namespace std;
# 
# int main() {
#     string Ali[4] = {"ijaz","hussain", "book", "work"};
#     cout <<Ali[0];
#     return 0;
# }
#

"""**Change an Array Element**

To change the value of a specific element, refer to the index number:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#     string hussain[4] = {"ali","abbas","summar","ayan"};
#     hussain[0]="haya";
#     cout <<hussain[0];
#     return 0;
# }

"""##**11.1-C++ Arrays and Loops**

You can loop through the array elements with the for loop.

The following example outputs all elements in the cars array:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#     int i;
#     string ali[4] = {"shahzad","sohail","hamza","haya"};
#     for( i = 0; i < 4; i++) {
#         cout << i << ":" <<ali[i] << "\n";
#     }
#     return 0;
# }

"""## **11.2-C++ Omit Array Size** 

You don't have to specify the size of the array. But if you don't, it will only be as big as the elements that are inserted into it:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#     int i;
#     string ali[] = {"hello", "world","key","school"};
#     for(i =0; i < 4; i++) {
#         cout << i << ":" <<ali[i] << "\n"; 
#     }
#     return 0;
# }
#

"""#**12-C++ References**

 A reference variable is a "reference" to an existing variable, and it is created with the & operator:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#     string ali = "pizza";
#     string &meal = ali;
# 
#     cout << ali <<endl;
#     cout << meal <<endl;
#     return 0;
# }
#

"""#**13-C++ Memory Address**

In the example from the previous page, the & operator was used to create a reference variable. But it can also be used to get the memory address of a variable; which is the location of where the variable is stored on the computer.

When a variable is created in C++, a memory address is assigned to the variable. And when we assign a value to the variable, it is stored in this memory address.

To access it, use the & operator, and the result will represent where the variable is stored:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int main() {
#     string food = "pizza";
# 
#     cout <<&food;
#     return 0;
# }
#

"""#**14-C++ Pointers**

You learned from the previous chapter, that we can get the memory address of a variable by using the & operator:

A pointer however, is a variable that stores the memory address as its value.


A pointer variable points to a data type (like int or string) of the same type, and is created with the * operator. The address of the variable you're working with is assigned to the pointer:

**Example explained**

Create a pointer variable with the name ptr, that points to a string variable, by using the asterisk sign * (string* ptr). Note that the type of the pointer has to match the type of the variable you're working with.

Use the & operator to store the memory address of the variable called food, and assign it to the pointer.

Now, ptr holds the value of food's memory address.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
#  int main(){
#      string food = "pizza";
#      string* ptr = &food;
# 
#      cout << food <<endl;
#      cout << &food <<endl;
#      cout << ptr <<endl;
#      return 0;
#      }
#

"""#**15-C++ Functions**

A function is a block of code which only runs when it is called.

You can pass data, known as parameters, into a function.

Functions are used to perform certain actions, and they are important for reusing code: Define the code once, and use it many times.

**Create a Function**

C++ provides some pre-defined functions, such as main(), which is used to execute code. But you can also create your own functions to perform certain actions.

To create (often referred to as declare) a function, specify the name of the function, followed by parentheses ():

**Syntax**

void myFunction() {
  // code to be executed
}

**Example Explained**

- myFunction() is the name of the function
- void means that the function does not have a return  value. You will learn more about return values later in the next chapter
- inside the function (the body), add code that defines what the function should do

**Call a Function**

Declared functions are not executed immediately. They are "saved for later use", and will be executed later, when they are called.

To call a function, write the function's name followed by two parentheses () and a semicolon ;

In the following example, myFunction() is used to print a text (the action), when it is called:

**Example**

Inside main, call myFunction():



"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# void pakistan() {
#     cout << "long live pakistan!";
# }
# int main(){
#     cout <<"first output"<<endl;
#   pakistan();
#   cout <<"second output"<<endl;
#    pakistan();
#    return 0;
# }
#



"""**Function Declaration and Definition**

A C++ function consist of two parts:

- Declaration: the function's name, return type, and parameters (if any)
- Definition: the body of the function (code to be executed)

Note: If a user-defined function, such as myFunction() is declared after the main() function, an error will occur. It is because C++ works from top to bottom; which means that if the function is not declared above main(), the program is unaware of it:

"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# void myFunction() {
#   cout << "I just got executed!";
# }
# 
# 
# int main() {
#   myFunction();
#   return 0;
# }
#

"""##**15.1-C++ Function Parameters**

Information can be passed to functions as a parameter. Parameters act as variables inside the function.

Parameters are specified after the function name, inside the parentheses. You can add as many parameters as you want, just separate them with a comma:

When a parameter is passed to the function, it is called an argument. So, from the example above: fname is a parameter, while Liam, Jenny and Anja are arguments.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# void hussain(string word) {
#     cout << word <<endl;
# }
#     int main(){
#         hussain("school");
#         hussain("book");
#         hussain("pen");
#         hussain("pencial");
#         return 0;
#     }

"""##**15.2-C++ Default Parameters** 

You can also use a default parameter value, by using the equals sign (=).

If we call the function without an argument, it uses the default value ("Norway"):

A parameter with a default value, is often known as an "optional parameter". From the example above, country is an optional parameter and "Norway" is the default value.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# void shahzad(string name ="haider"){
# cout << name <<endl;
# }
# int main(){
# shahzad("haya");
# shahzad("summar");
# shahzad();
# shahzad("ayan");
# return 0;
# }
#

"""##**15.3-C++ Multiple Parameters** 

Inside the function, you can add as many parameters as you want:

Note that when you are working with multiple parameters, the function call must have the same number of arguments as there are parameters, and the arguments must be passed in the same order.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# void work(string shahzad, int age) {
#      cout << shahzad << " endl. " << age << " years old.endl";
# }
# int main(){
#     work("haya",5);
#     work("summar",11);
#     work("mahdi",4);
#     work("lahar",10);
#     return 0;
# }
#

"""##**15.4-C++ The Return Keyword**

The void keyword, used in the previous examples, indicates that the function should not return a value. If you want the function to return a value, you can use a data type (such as int, string, etc.) instead of void, and use the return keyword inside the function:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# int world(int x, int y) {
#     int sum = x+y;
#     return sum;
# }
# int main(){
#     int finalsum = world(5 , 7);
#     cout <<finalsum<<endl;
#     return 0;
# }

"""##**15.5-C++ Function Overloading**

With function overloading, multiple functions can have the same name with different parameters:

Instead of defining two functions that should do the same thing, it is better to overload one.

In the example below, we overload the plusFunc function to work for both int and double:

Note: Multiple functions can have the same name as long as the number and/or type of parameters are different.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# int myfunction(int x, int y) {
#     return  x + y;
# }
# double myfunction(double x, double y) {
#     return x + y;
# }
# int main(){
#     int number1 = myfunction(8 , 6);
#     double number2 = myfunction(5.5 , 2.5);
#     cout <<"Int: " << number1<<endl;
#     cout <<"Double: " <<number2<<endl;
#     return 0;
# }

"""#**16-C++ OOP**

**C++ What is OOP?**

OOP stands for Object-Oriented Programming.

Procedural programming is about writing procedures or functions that perform operations on the data, while object-oriented programming is about creating objects that contain both data and functions.

Object-oriented programming has several advantages over procedural programming:

- OOP is faster and easier to execute
- OOP provides a clear structure for the programs
- OOP helps to keep the C++ code DRY "Don't Repeat Yourself", and makes the code easier to maintain, modify and debug
- OOP makes it possible to create full reusable applications with less code and shorter development time.

##**16.1-C++ What are Classes and Objects?** 

Classes and objects are the two main aspects of object-oriented programming.

Look at the following illustration to see the difference between class and objects:

So, a class is a template for objects, and an object is an instance of a class.

When the individual objects are created, they inherit all the variables and functions from the class.

You will learn much more about classes and objects in the next chapter.

![](https://drive.google.com/uc?export=view&id=1OiI0OM8SZDffAmtpczf56BYziR6f_b2T)

##**16.2-C++ Classes and Objects**
 
 C++ is an object-oriented programming language.

Everything in C++ is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.

Attributes and methods are basically variables and functions that belongs to the class. These are often referred to as "class members".

A class is a user-defined data type that we can use in our program, and it works as an object constructor, or a "blueprint" for creating objects.

**Create a Class**
To create a class, use the class keyword:
Create a class called "MyClass":
"""

class MyClass {       // The class
  public:             // Access specifier
    int myNum;        // Attribute (int variable)
    string myString;  // Attribute (string variable)
};

"""**Example explained**
- The class keyword is used to create a class called MyClass.
- The public keyword is an access specifier, which specifies that members (attributes and methods) of the class are accessible from outside the class. You will learn more about access specifiers later.

- Inside the class, there is an integer variable myNum and a string variable myString. When variables are declared within a class, they are called attributes.

- At last, end the class definition with a semicolon ;.

##**16.3-Create an Object** 

In C++, an object is created from a class. We have already created the class named MyClass, so now we can use this to create objects.

To create an object of MyClass, specify the class name, followed by the object name.

To access the class attributes (myNum and myString), use the dot syntax (.) on the object:

**Example**
Create an object called "myObj" and access the attributes:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class MyClass {       //  class
#   public:             //  specifier
#     int myNum;        // Attribute (int )
#     string myString;  // Attribute (string)
# };
# 
# int main() {
#   MyClass myObj;  //  object of MyClass
# 
#   // Access attributes and set values
#   myObj.myNum = 70;
#   myObj.myString = "pakistan";
# 
#   // Print values
#   cout << myObj.myNum <<endl;
#   cout << myObj.myString <<endl; 
#   return 0;
# }
#

"""##**16.4-Multiple Objects**
You can create multiple objects of one class:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class car {
#     public:
#     string brand;
#     string model;
#     int year;
# };
# 
# int main(){
#     car carobj1;
#     carobj1.brand = "BMW";
#     carobj1.model = "vvt";
#     carobj1.year = 2002;
# 
#     car carobj2;
#     carobj2.brand = "toyota";
#     carobj2.model = "vvtr";
#     carobj2.year = 2006;
# 
#     cout << carobj1.brand << " " << carobj1.model << " " << carobj1.year <<endl;
#     cout << carobj2.brand << " " <<carobj2.model << " " << carobj2.year <<endl;
#     return 0;
# }

"""##**16.5-C++ Class Methods**
Methods are functions that belongs to the class.

There are two ways to define functions that belongs to a class:

- Inside class definition
- Outside class definition

In the following example, we define a function inside the class, and we name it "myMethod".

**Note**: You access methods just like you access attributes; by creating an object of the class and by using the dot syntax (.):

**inside**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# class pakistan {
#     public:
#     void mymethod() {
#         cout <<"pakistani people";
#     }
#     }; 
#     int main() {
#         pakistan myobj;
#         myobj.mymethod();
#         return 0;
#     }
#

"""**0utside example**"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# class myclass {
#     public:
#     void mymethod();
# };
# void myclass::mymethod(){
#     cout << "pakistan";
# }
#  int main(){
#      myclass myobj;
#      myobj.mymethod();
#      return 0;
#  }

"""#**17-C++ Constructors**

A constructor in C++ is a special method that is automatically called when an object of a class is created.

To create a constructor, use the same name as the class, followed by parentheses ():
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class shahzad {     // class
#   public:           //  specifier
#     shahzad() {     // Constructor
#       cout << "Hello World!";
#     }
# };
# 
# int main() {
#   shahzad myObj;    // this will call the constructor
#   return 0;
# }
#

"""#**17.1-Constructor Parameters** 

Constructors can also take parameters (just like regular functions), which can be useful for setting initial values for attributes.

The following class have brand, model and year attributes, and a constructor with different parameters. Inside the constructor we set the attributes equal to the constructor parameters (brand=x, etc). When we call the constructor (by creating an object of the class), we pass parameters to the constructor, which will set the value of the corresponding attributes to the same:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class Car {        //  class
#   public:          //  specifier
#     string brand;  // Attribute
#     string model;  // Attribute
#     int year;      // Attribute
#     Car(string x, string y, int z) {  // Constructor with parameters
#       brand = x;
#       model = y;
#       year = z;
#     }
# };
# 
# int main() {
#   // Create Car objects and call the constructor with different values
#   Car carObj1("toyota", "vvt", 2006);
#   Car carObj2("honda", "vvtr", 2012);
# 
#   // Print values
#   cout << carObj1.brand << " " << carObj1.model << " " << carObj1.year << endl;
#   cout << carObj2.brand << " " << carObj2.model << " " << carObj2.year << endl;
#   return 0;
# }
#

"""#**18-C++ Access Specifiers**
By now, you are quite familiar with the public keyword that appears in all of our class examples:

The public keyword is an access specifier. Access specifiers define how the members (attributes and methods) of a class can be accessed. In the example above, the members are public - which means that they can be accessed and modified from outside the code.

However, what if we want members to be private and hidden from the outside world?

In C++, there are three access specifiers:

- public - members are accessible from outside the class
- private - members cannot be accessed (or viewed) from outside the class
- protected - members cannot be accessed from outside the class, however, they can be accessed in inherited classes. You will learn more about Inheritance later.

In the following example, we demonstrate the differences between public and private members:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu 
# #include <iostream>
# using namespace std;
# 
# class myclass{     // class
#     public:        // public acccess specifier
#     int x;         // attributes
#     private:      // private access specifier
#     int y;         // attributes
# 
# };
# 
# int main() {
#   myclass myObj;
#   myObj.x = 90;  
#   //myObj.y = 60;  
#   return 0;
# }
#

"""#**18-C++ Encapsulation**
 
 The meaning of Encapsulation, is to make sure that "sensitive" data is hidden from users. To achieve this, you must declare class variables/attributes as private (cannot be accessed from outside the class). If you want others to read or modify the value of a private member, you can provide public get and set methods.

 **Access Private Members**

 
To access a private attribute, use public "get" and "set" methods:

**Example explained**
The salary attribute is private, which have restricted access.

The public setSalary() method takes a parameter (s) and assigns it to the salary attribute (salary = s).

The public getSalary() method returns the value of the private salary attribute.

Inside main(), we create an object of the Employee class. Now we can use the setSalary() method to set the value of the private attribute to 50000. Then we call the getSalary() method on the object to return the value.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class Employee {
#   private:
#     int salary;
# 
#   public:
#     void setSalary(int s) {
#       salary = s;
#     }
#     int getSalary() {
#       return salary;
#     }
# };
# 
# int main() {
#   Employee myObj;
#   myObj.setSalary(20000);
#   cout << myObj.getSalary();
#   return 0;
# }
#

"""#**19-C++ Inheritance** 

In C++, it is possible to inherit attributes and methods from one class to another. We group the "inheritance concept" into two categories:

- derived class (child) - the class that inherits from another class
- base class (parent) - the class being inherited from
To inherit from a class, use the : symbol.

In the example below, the Car class (child) inherits the attributes and methods from the Vehicle class (parent):
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# // Base class
# class Vehicle {
#   public: 
#     string brand = "toyota";
#     void honk() {
#       cout << "Tuut, tuut"<<endl;
#     }
# };
# 
# // Derived class
# class Car: public Vehicle {
#   public: 
#     string model = "Mustang";
# };
# 
# int main() {
#   Car myCar;
#   myCar.honk();
#   cout << myCar.brand + " " + myCar.model;
#   return 0;
# }
# 
#

"""##**19.1-C++ Multilevel Inheritance** 

 class can also be derived from one class, which is already derived from another class.

In the following example, MyGrandChild is derived from class MyChild (which is derived from MyClass)
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# // Parent class
# class MyClass {
#   public: 
#     void myFunction() {
#       cout << "Some content in parent class." ;
#     }
# };
# 
# // Child class
# class MyChild: public MyClass {
# };
# 
# // Grandchild class 
# class MyGrandChild: public MyChild {
# };
# 
# int main() {
#   MyGrandChild myObj;
#   myObj.myFunction();
#   return 0;
# }
#

"""##**19.2-Multiple Inheritance**

A class can also be derived from more than one base class, using a comma-separated list:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class myclass {
#     public:
#     void myfunction() {
#         cout <<"shahzad hussain"<<endl;
#     }
# };
# class myotherclass {
#     public:
#     void myotherfunction(){
#         cout <<"pakistan"<<endl;
#     }
# };
# class mychildclass:public myclass,public myotherclass{
#     
# };
# int main() {
#     mychildclass myobj;
#     myobj.myfunction();
#     myobj.myotherfunction();
#     return 0;
# }

"""#**19.3-Access Specifiers**

You learned from the Access Specifiers chapter that there are three specifiers available in C++. Until now, we have only used public (members of a class are accessible from outside the class) and private (members can only be accessed within the class). The third specifier, protected, is similar to private, but it can also be accessed in the inherited class:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# // Base class
# class Employee  {
#   protected:  // Protected access specifier
#     int salary;
# };
# 
# // Derived class
# class Programmer: public Employee {
#   public:
#     int bonus;
#     void setSalary(int s) {
#       salary = s;
#     }
#     int getSalary() {
#       return salary;
#     }
# };
# 
# int main() {
#   Programmer myObj;
#   myObj.setSalary(70000);
#   myObj.bonus = 1500;
#   cout << "Salary: " << myObj.getSalary() << "\n";
#   cout << "Bonus: " << myObj.bonus << "\n";
#   return 0;
# }
#

"""#**20-Polymorphism** 

Polymorphism means "many forms", and it occurs when we have many classes that are related to each other by inheritance.

Like we specified in the previous chapter; Inheritance lets us inherit attributes and methods from another class. Polymorphism uses those methods to perform different tasks. This allows us to perform a single action in different ways.

For example, think of a base class called Animal that has a method called animalSound(). Derived classes of Animals could be Pigs, Cats, Dogs, Birds - And they also have their own implementation of an animal sound (the pig oinks, and the cat meows, etc.):

Remember from the Inheritance chapter that we use the : symbol to inherit from a class.

Now we can create Pig and Dog objects and override the animalSound() method:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# class animal{
#     public:
#     void animalsound(){
#         cout <<"animal make a sound"<<endl;
#     }
# };
# class pig:public animal{
#     public:
#     void animalsound(){
#         cout <<"sound of wildforest"<<endl;
#     }
# };
# class dog: public animal{
#     public:
#     void animalsound(){
#         cout <<"sound of gangal"<<endl;
#     }
# };
# 
# int main(){
#     animal myanimal;
#     pig mypig;
#     dog mydog;
# 
#     myanimal.animalsound();
#     mypig.animalsound();
#     mydog.animalsound();
#     return 0;
# 
# }

"""#**Reference** 
C++ Tutorial
https://www.w3schools.com/cpp/cpp_strings.asp

https://www.learn-cpp.org/en/Variables_and_Types

How to Run CUDA C or C++ on Jupyter (Google Colab)

https://www.wikihow.com/Run-CUDA-C-or-C%2B%2B-on-Jupyter-(Google-Colab)

Code block
http://www.codeblocks.org/downloads/26

Freebootcamp
https://www.freecodecamp.org/

ntroduction to C++ Programming in Urdu
https://www.youtube.com/watch?v=dnCO124Uk1o

6 Sentiment Analysis Projects with Python

https://amankharwal.medium.com/6-sentiment-analysis-projects-with-python-1fdd3d43d90f
"""